### ISSUE TITLE
Fix required for NGO's registration page

### ISSUE THREAD

**Issue by 1HazArd1** [1HazArd1/Samarpan#13]
1. Data is not collecting to the firebase.
2. Showing a toast in the app saying "The email address is badly formatted"

https://user-images.githubusercontent.com/77063438/191573160-5f7a2cf1-7e7d-4899-b0c4-994ff8d2b5e6.mp4

**Comment by Rohit-554** [comment]
Hi 😊, 
I want to work on this

**Comment by 1HazArd1** [comment]
Ok, please let me know if you don't understand the bug

**Comment by Rohit-554** [comment]
> Ok, please let me know if you don't understand the bug

Yup, I understood the bug

**Comment by 1HazArd1** [comment]
Fixed the issue problem with the null safety just added null safety asser

https://user-images.githubusercontent.com/77063438/193323633-63b09852-5aa4-4ab2-b7dc-5a996b07a1cd.mp4

tion for the data(s)
