### ISSUE TITLE
create the user profile section 

### ISSUE THREAD

**Issue by Rohit-554** [1HazArd1/Samarpan#16]
When you register with the application, in the dashboard in the top right there is a profile button, when tapped it should open up a seperate fragment that shows user details, for now only display name and email and a default photo, While contributing Rember the guidelines as given in [contribution.md](https://github.com/Diversion2k22/Samarpan/blob/master/CONTRIBUTION.md).
<br>
<b> if you have any doubts feel free to ask here or in </b> [discord](https://discord.gg/baZJFETbjJ)

**Comment by SegFault03** [comment]
I'd like to work on this issue. Please assign this to me.

**Comment by Rohit-554** [comment]
Sure, go ahead
